DROP TABLE IF EXISTS service_selections CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS selections CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS composers CASCADE;