DROP TABLE IF EXISTS service_pieces CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS pieces CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS composers CASCADE;